# Generated by Django 3.0.4 on 2020-04-05 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZCategory",
            fields=[
                (
                    "identifier",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("label", models.CharField(max_length=256, null=True)),
                ("hierarchy_index", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ZCategory_Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.ZCategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZFavorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZProduct",
            fields=[
                (
                    "code",
                    models.BigIntegerField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("brands", models.CharField(max_length=200, verbose_name="Marque")),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("url", models.URLField(verbose_name="URL")),
                ("stores", models.IntegerField(null=True, verbose_name="Stores")),
                (
                    "nutrition_grades",
                    models.IntegerField(null=True, verbose_name="Nutri-Score"),
                ),
                ("nova_group", models.IntegerField(null=True, verbose_name="Nova")),
                (
                    "nutrition_score",
                    models.SmallIntegerField(null=True, verbose_name="Nutrition score"),
                ),
                (
                    "nutrition_score_beverage",
                    models.SmallIntegerField(
                        null=True, verbose_name="Nutrition score beverage"
                    ),
                ),
                (
                    "unique_scans_n",
                    models.SmallIntegerField(null=True, verbose_name="Popularité"),
                ),
                (
                    "created_t",
                    models.BigIntegerField(null=True, verbose_name="Date de création"),
                ),
                (
                    "last_modified_t",
                    models.BigIntegerField(
                        default=0, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "update_t",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Date d'enregistrement",
                    ),
                ),
                ("image_url", models.URLField(null=True, verbose_name="Image URL")),
                ("firstSearchDate", models.DateTimeField(auto_now_add=True)),
                ("lastSearchDate", models.DateTimeField(auto_now_add=True)),
                (
                    "alternatives",
                    models.ManyToManyField(
                        blank=True, related_name="substituted", to="product.ZProduct"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        through="product.ZCategory_Product",
                        to="product.ZCategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.CreateModel(
            name="ZSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "favorite_alternatives",
                    models.ManyToManyField(
                        blank=True, related_name="zsearches", to="product.ZFavorite"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.ZProduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="zproduct",
            name="searchers",
            field=models.ManyToManyField(
                blank=True,
                related_name="searches",
                through="product.ZSearch",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zproduct",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorites",
                through="product.ZFavorite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zfavorite",
            name="favorite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.ZProduct"
            ),
        ),
        migrations.AddField(
            model_name="zfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="zcategory_product",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.ZProduct"
            ),
        ),
        migrations.AddConstraint(
            model_name="zproduct",
            constraint=models.UniqueConstraint(
                fields=("brands", "name"), name="product_identifier_unique"
            ),
        ),
    ]
