# Generated by Django 3.0.4 on 2020-04-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_auto_20200405_0321"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zproduct",
            name="product_identifier_unique",
        ),
    ]
