# Generated by Django 3.0.3 on 2020-02-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True)),
                ('brand', models.IntegerField(null=True)),
                ('name', models.IntegerField(null=True)),
                ('store', models.IntegerField(null=True)),
                ('category_hierarchy', models.IntegerField(null=True)),
                ('nutrition_grade', models.IntegerField(null=True)),
                ('nova_group', models.IntegerField(null=True)),
                ('url', models.URLField()),
                ('picture', models.URLField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isSearched', models.BooleanField(default=False)),
                ('firstSearchDate', models.DateTimeField(auto_now_add=True)),
                ('lastSearchDate', models.DateTimeField(auto_now_add=True)),
                ('isfavorite', models.BooleanField(default=False)),
                ('contact', models.ManyToManyField(blank=True, related_name='product', to='product.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('product', models.ManyToManyField(blank=True, related_name='category', to='product.Product')),
            ],
        ),
    ]
