# Generated by Django 3.0.3 on 2020-02-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ZCategory',
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='ZContact',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ZProduct',
        ),
    ]
