# Generated by Django 3.0.3 on 2020-03-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200302_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='zproduct',
            name='alternative',
            field=models.ManyToManyField(blank=True, related_name='_zproduct_alternative_+', to='product.ZProduct'),
        ),
    ]
