# Generated by Django 3.0.4 on 2020-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_zproduct_alternative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zcontact',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='zproduct',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='zproduct',
            name='brand',
            field=models.CharField(max_length=200, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='zproduct',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='product.ZContact'),
        ),
        migrations.AlterField(
            model_name='zproduct',
            name='reference',
            field=models.IntegerField(null=True, verbose_name='Code'),
        ),
    ]
