# Generated by Django 3.0.4 on 2020-03-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200325_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZAddress',
        ),
        migrations.DeleteModel(
            name='ZRole',
        ),
    ]
