# Generated by Django 3.0.4 on 2020-04-01 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_auto_20200325_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='zproduct',
            name='contact',
        ),
        migrations.DeleteModel(
            name='ZContact',
        ),
        migrations.AddField(
            model_name='zsearch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ZProduct'),
        ),
        migrations.AddField(
            model_name='zsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zproduct',
            name='user',
            field=models.ManyToManyField(related_name='_zproduct_user_+', through='product.ZSearch', to=settings.AUTH_USER_MODEL),
        ),
    ]
