# Generated by Django 3.0.4 on 2020-04-01 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_auto_20200401_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zproduct',
            name='user',
        ),
        migrations.AddField(
            model_name='zproduct',
            name='search',
            field=models.ManyToManyField(related_name='_zproduct_search_+', through='product.ZSearch', to=settings.AUTH_USER_MODEL),
        ),
    ]
