# Generated by Django 3.0.4 on 2020-04-01 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_auto_20200401_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zproduct',
            name='alternative',
        ),
        migrations.RemoveField(
            model_name='zproduct',
            name='search',
        ),
        migrations.AddField(
            model_name='zproduct',
            name='searches',
            field=models.ManyToManyField(blank=True, related_name='alternative', to='product.ZSearch'),
        ),
        migrations.AddField(
            model_name='zproduct',
            name='users',
            field=models.ManyToManyField(related_name='_zproduct_users_+', through='product.ZSearch', to=settings.AUTH_USER_MODEL),
        ),
    ]
