# Generated by Django 3.0.4 on 2020-04-01 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_auto_20200401_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zproduct',
            name='reference',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='zproduct',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_zproduct_users_+', through='product.ZSearch', to=settings.AUTH_USER_MODEL),
        ),
    ]
