# Generated by Django 3.0.4 on 2020-04-02 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_auto_20200402_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zproduct',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='zproduct',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='searches', through='product.ZSearch', to=settings.AUTH_USER_MODEL),
        ),
    ]
