# Generated by Django 3.0.4 on 2020-04-02 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_auto_20200402_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zsearch',
            old_name='product',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='zproduct',
            name='searches',
        ),
        migrations.AddField(
            model_name='zproduct',
            name='searchers',
            field=models.ManyToManyField(blank=True, related_name='searches', through='product.ZSearch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ZFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ZProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='zproduct',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='favorites', through='product.ZFavorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
