# Generated by Django 3.0.4 on 2020-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_zsearch_alternatives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zsearch',
            old_name='alternatives',
            new_name='favorite_alternatives',
        ),
        migrations.AddField(
            model_name='zproduct',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='_zproduct_alternatives_+', to='product.ZProduct'),
        ),
        migrations.AddConstraint(
            model_name='zproduct',
            constraint=models.UniqueConstraint(fields=('reference', 'brands', 'name'), name='product_identifier_unique'),
        ),
    ]
