# Generated by Django 3.0.4 on 2020-04-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200404_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zproduct',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='substituted', to='product.ZProduct'),
        ),
    ]
