# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'z_view\form.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.category_view = QtWidgets.QTreeView(self.groupBox_6)
        self.category_view.setObjectName("category_view")
        self.verticalLayout_2.addWidget(self.category_view)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.select_all_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.select_all_btn.setObjectName("select_all_btn")
        self.horizontalLayout_5.addWidget(self.select_all_btn)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.product_view = QtWidgets.QTreeView(self.groupBox_7)
        self.product_view.setObjectName("product_view")
        self.verticalLayout_3.addWidget(self.product_view)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.product_select_pbtn = QtWidgets.QPushButton(self.groupBox_10)
        self.product_select_pbtn.setObjectName("product_select_pbtn")
        self.horizontalLayout_3.addWidget(self.product_select_pbtn)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        self.horizontalLayout_2.addWidget(self.groupBox_7)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.alternative_view = QtWidgets.QTreeView(self.groupBox_4)
        self.alternative_view.setObjectName("alternative_view")
        self.verticalLayout_4.addWidget(self.alternative_view)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.alternative_select_pbtn = QtWidgets.QPushButton(self.groupBox_11)
        self.alternative_select_pbtn.setObjectName("alternative_select_pbtn")
        self.horizontalLayout_4.addWidget(self.alternative_select_pbtn)
        self.verticalLayout_4.addWidget(self.groupBox_11)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.favorite_view = QtWidgets.QTreeView(self.groupBox_5)
        self.favorite_view.setObjectName("favorite_view")
        self.verticalLayout_5.addWidget(self.favorite_view)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.favorite_remove_pbtn = QtWidgets.QPushButton(self.groupBox_13)
        self.favorite_remove_pbtn.setObjectName("favorite_remove_pbtn")
        self.horizontalLayout_8.addWidget(self.favorite_remove_pbtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.groupBox_13)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.altern_category_cbox = QtWidgets.QComboBox(self.groupBox_2)
        self.altern_category_cbox.setMinimumSize(QtCore.QSize(170, 0))
        self.altern_category_cbox.setObjectName("altern_category_cbox")
        self.horizontalLayout_6.addWidget(self.altern_category_cbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "Selection"))
        self.groupBox_6.setTitle(_translate("Form", "Category"))
        self.select_all_btn.setText(_translate("Form", "Select All"))
        self.groupBox_7.setTitle(_translate("Form", "Product"))
        self.product_select_pbtn.setText(_translate("Form", ">>"))
        self.groupBox_9.setTitle(_translate("Form", "Output"))
        self.groupBox_4.setTitle(_translate("Form", "Alternative"))
        self.alternative_select_pbtn.setText(_translate("Form", ">>"))
        self.groupBox_5.setTitle(_translate("Form", "Favorite"))
        self.favorite_remove_pbtn.setText(_translate("Form", "<<"))
        self.groupBox_2.setTitle(_translate("Form", "Alternative Category"))


