# Generated by Django 3.0.4 on 2020-03-31 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_zprofil_zuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZUser',
        ),
    ]
